#!/usr/bin/env python3
"""Generate examples/index.json and each skill's "Runnable examples" section.

One file describes every example (#377): its script, the skills it proves,
whether it ships a gallery render, the oldest Blender it runs on, the command
to run it, every smoke falsifier with its expected exit, and the README's
exit-code table. Inputs, all hand-edited elsewhere:

    examples/skills.json         example -> skills it proves (edit this one)
    tests/smoke/catalog.json     scripts, min_version, falsifiers
    examples/gallery.json        which examples render
    examples/<name>/README.md    one-line summary and exit-code table

The section between the markers in skills/*/SKILL.md is rewritten from the
index; everything outside the markers is left alone.

    python scripts/build_examples_index.py          write index.json and SKILL.md sections
    python scripts/build_examples_index.py --check  exit 1 if either is stale or the mapping is invalid
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPO_URL = "https://github.com/TMHSDigital/Blender-Developer-Tools"
BEGIN = "<!-- examples:begin (generated by scripts/build_examples_index.py from examples/skills.json; do not edit) -->"
END = "<!-- examples:end -->"
# Skills whose examples are still to be written. Listing one that has an
# example is an error, so this shrinks as #378 lands.
PENDING = {
    "addon-scaffolding": "#378",
    "bl-info-migration": "#378",
    "ui-panels": "#378",
}
EXIT_ROW = re.compile(r"^\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*$", re.M)
SENTENCE = re.compile(r"(.+?[.!?])(?:\s|$)", re.S)
MD_LINK = re.compile(r"\[([^\]]+)\]\([^)]+\)")
MAX_SUMMARY = 200


def _summary(readme: str, teaches: str | None) -> str:
    """First sentence of the gallery's `teaches` line, or for a check-only
    example, of the README's first paragraph after the title.

    A sentence ends at '.', '!' or '?' followed by whitespace, so a dotted API
    path such as `bmesh.ops` never cuts it short (the PR #68 alt-text bug).
    """
    if teaches:
        body = teaches
    else:
        paras = [p for p in re.split(r"\n\s*\n", readme) if p.strip()]
        body = next((p for p in paras if not p.lstrip().startswith(("#", "<", "!", "|", "```"))), "")
    text = MD_LINK.sub(r"\1", " ".join(body.split()))
    m = SENTENCE.match(text)
    text = (m.group(1) if m else text).strip()
    if len(text) <= MAX_SUMMARY:
        return text
    # Long lead sentences list parts after a dash or colon; keep the claim.
    for sep in (" — ", ": ", "; ", ", "):
        for m in re.finditer(re.escape(sep), text):
            head = text[:m.start()]
            if 40 <= len(head) <= MAX_SUMMARY and head.count("(") == head.count(")"):
                return _close_code(head) + "."
    return _close_code(text[:MAX_SUMMARY].rsplit(" ", 1)[0]) + "…"


def _close_code(text: str) -> str:
    """Drop a trailing half code span so a cut never leaves a lone backtick."""
    return text.rsplit("`", 1)[0].rstrip(" ,;:(") if text.count("`") % 2 else text.rstrip(" ,;:(")


def _exit_codes(readme: str) -> dict[str, str]:
    return {code: desc for code, desc in EXIT_ROW.findall(readme)}


def build_index() -> tuple[list[dict], list[str]]:
    errors: list[str] = []
    mapping = json.loads((ROOT / "examples" / "skills.json").read_text(encoding="utf-8"))
    mapping.pop("_comment", None)
    catalog = json.loads((ROOT / "tests" / "smoke" / "catalog.json").read_text(encoding="utf-8"))
    gallery = {Path(e["dir"]).name: e["teaches"] for e in
               json.loads((ROOT / "examples" / "gallery.json").read_text(encoding="utf-8"))["examples"]}
    skills = sorted(p.parent.name for p in (ROOT / "skills").glob("*/SKILL.md"))
    dirs = sorted(d.name for d in (ROOT / "examples").iterdir()
                  if d.is_dir() and not d.name.startswith((".", "_")))

    for name in sorted(set(dirs) - set(mapping)):
        errors.append(f"examples/{name} is missing from examples/skills.json")
    for name in sorted(set(mapping) - set(dirs)):
        errors.append(f"examples/skills.json lists {name}, which is not an example directory")
    for name, listed in mapping.items():
        for s in listed:
            if s not in skills:
                errors.append(f"examples/skills.json: {name} names unknown skill {s!r}")

    index = []
    for name in dirs:
        rows = [r for r in catalog if Path(r["script"]).parts[:2] == ("examples", name)]
        if not rows:
            errors.append(f"examples/{name} has no tests/smoke/catalog.json row")
            continue
        primary = next((r for r in rows if r["name"] == name), rows[0])
        readme_path = ROOT / "examples" / name / "README.md"
        readme = readme_path.read_text(encoding="utf-8") if readme_path.is_file() else ""
        falsifiers = []
        for r in rows:
            for f in r.get("falsifiers", []):
                entry = {"args": f["args"]}
                if "expect_exit" in f:
                    entry["expect_exit"] = f["expect_exit"]
                if f.get("expect_sidecar_fail"):
                    entry["expect_sidecar_fail"] = True
                floor = f.get("min_version") or r.get("min_version")
                if floor:
                    entry["min_version"] = floor
                if entry not in falsifiers:
                    falsifiers.append(entry)
        index.append({
            "name": name,
            "path": f"examples/{name}/",
            "script": primary["script"],
            "skills": mapping.get(name, []),
            "render": name in gallery,
            "min_version": primary.get("min_version", "4.5"),
            "run": f"blender --background --python {primary['script']}",
            "summary": _summary(readme, gallery.get(name)),
            "falsifiers": falsifiers,
            "exit_codes": _exit_codes(readme),
        })

    proven = {s for e in index for s in e["skills"]}
    for s in skills:
        if s not in proven and s not in PENDING:
            errors.append(f"skills/{s} has no runnable example in examples/skills.json")
        if s in proven and s in PENDING:
            errors.append(f"skills/{s} now has an example; drop it from PENDING in {Path(__file__).name}")
    return index, errors


def _flag(f: dict) -> str:
    args = " ".join(f["args"])
    if f.get("expect_sidecar_fail"):
        return f"`{args}` (harness fails the sidecar)"
    return f"`{args}` (exit {f['expect_exit']})"


def skill_section(skill: str, index: list[dict]) -> str:
    lines = [BEGIN, "## Runnable examples", ""]
    mine = [e for e in index if skill in e["skills"]]
    if not mine:
        lines.append(f"No runnable example proves this skill yet (tracked in "
                     f"[{PENDING[skill]}]({REPO_URL}/issues/{PENDING[skill].lstrip('#')})).")
    else:
        lines.append("Each example runs headless, asserts the contract, and exits non-zero when it breaks. "
                     "Run one with `blender --background --python <script> --`; pass a falsifier flag to "
                     "watch the check fail.")
        lines.append("")
        for e in mine:
            first = _flag(e["falsifiers"][0]) if e["falsifiers"] else ""
            since = f" Blender {e['min_version']}+." if e["min_version"] != "4.5" else ""
            lines.append(f"- [`{e['name']}`]({REPO_URL}/tree/main/examples/{e['name']}): {e['summary']}"
                         f"{since} Falsify: {first}.")
    lines += ["", END]
    return "\n".join(lines)


def render_skill(text: str, section: str) -> str:
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1]
        return head + section + tail
    # First run: place the section before "## References" when the skill has one.
    m = re.search(r"^## References\b", text, re.M)
    if m:
        return text[:m.start()] + section + "\n\n" + text[m.start():]
    return text.rstrip("\n") + "\n\n" + section + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    index, errors = build_index()
    if errors:  # a broken mapping cannot render the skill sections
        for e in errors:
            print(f"::error::{e}", file=sys.stderr)
        return 1
    want ={ROOT / "examples" / "index.json": json.dumps(index, indent=2, ensure_ascii=False) + "\n"}
    for p in sorted((ROOT / "skills").glob("*/SKILL.md")):
        want[p] = render_skill(p.read_text(encoding="utf-8"), skill_section(p.parent.name, index))
    stale = [p for p, text in want.items()
             if not p.is_file() or p.read_text(encoding="utf-8") != text]
    if a.check:
        for p in stale:
            errors.append(f"{p.relative_to(ROOT).as_posix()} is stale; run python scripts/{Path(__file__).name}")
    elif not errors:
        for p in stale:
            p.write_text(want[p], encoding="utf-8", newline="\n")
    for e in errors:
        print(f"::error::{e}", file=sys.stderr)
    if errors:
        return 1
    print(f"examples index: {len(index)} examples, {sum(1 for e in index if e['skills'])} linked to skills; "
          f"{'checked' if a.check else f'wrote {len(stale)} file(s)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
