#!/usr/bin/env python3
"""Generate claude/blender-rules.md from rules/*.mdc.

Claude Code does not read Cursor .mdc rules. This writes a plain-markdown
summary (one section per rule: description, load scope, link to the full rule)
that a Claude Code user imports from their own CLAUDE.md with
``@path/to/Blender-Developer-Tools/claude/blender-rules.md``.

    python scripts/build_claude_rules.py          # rewrite the file
    python scripts/build_claude_rules.py --check  # exit 1 if it is stale (CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "claude" / "blender-rules.md"


def parse(path: Path) -> tuple[str, list[str]]:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise SystemExit(f"{path}: missing frontmatter")
    front = m.group(1)
    desc = re.search(r"^description:\s*(.+)$", front, re.M)
    if not desc:
        raise SystemExit(f"{path}: missing description")
    globs = re.findall(r'^\s+-\s+"?([^"\n]+)"?\s*$', front.split("globs:", 1)[-1], re.M)
    return desc.group(1).strip(), globs


def render() -> str:
    lines = [
        "# Blender Developer Tools rules (Claude Code)",
        "",
        "<!-- Generated by scripts/build_claude_rules.py from rules/*.mdc. Do not edit. -->",
        "",
        "Apply these when writing or reviewing Blender Python. Each rule links to the",
        "full version with Wrong/Right examples.",
        "",
    ]
    for path in sorted((REPO / "rules").glob("*.mdc")):
        desc, globs = parse(path)
        lines += [
            f"## {path.stem}",
            "",
            desc,
            "",
            f"Applies to: {', '.join(f'`{g}`' for g in globs) or 'n/a'}. Full rule: `rules/{path.name}`.",
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    new = render()
    if "--check" in sys.argv:
        old = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if old != new:
            print("claude/blender-rules.md is stale; run python scripts/build_claude_rules.py", file=sys.stderr)
            return 1
        print("claude/blender-rules.md is up to date")
        return 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(new, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
