#!/usr/bin/env python3
"""Generate the Claude Code copies of rules/*.mdc.

Claude Code does not read Cursor .mdc rules. This writes the same plain-markdown
summary (one section per rule: description, load scope, link to the full rule
with its Wrong/Right examples) to two places:

- claude/skills/blender-rules/SKILL.md: a skill the plugin ships
  (.claude-plugin/plugin.json "skills"), so plugin users get the rules with no
  second clone; Claude loads it when writing or reviewing bpy code.
- claude/blender-rules.md: for always-on use, imported from a project's
  CLAUDE.md with ``@path/to/Blender-Developer-Tools/claude/blender-rules.md``.

Links are absolute GitHub URLs so they open from an installed plugin, a
checkout, or a CLAUDE.md import alike.

    python scripts/build_claude_rules.py          # rewrite the file
    python scripts/build_claude_rules.py --check  # exit 1 if it is stale (CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "claude" / "blender-rules.md"
SKILL_OUT = REPO / "claude" / "skills" / "blender-rules" / "SKILL.md"
RULE_URL = "https://github.com/TMHSDigital/Blender-Developer-Tools/blob/main/rules/"
SKILL_FRONT = """---
name: blender-rules
description: Blender Python anti-pattern rules (bmesh leaks, bpy.ops in loops, deprecated context-copy overrides, bulk mesh writes, prop annotations and context guards, Extensions manifest, import scale, export modifiers, glTF/FBX axis RNA). Use when writing, reviewing or fixing any bpy / Blender add-on or script code.
---

"""


def parse(path: Path) -> tuple[str, list[str]]:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise SystemExit(f"{path}: missing frontmatter")
    front = m.group(1)
    desc = re.search(r"^description:\s*(.+)$", front, re.M)
    if not desc:
        raise SystemExit(f"{path}: missing description")
    globs = re.findall(r'^\s+-\s+"?([^"\n]+)"?\s*$', front.split("globs:", 1)[-1], re.M)
    return desc.group(1).strip(), globs


def render() -> str:
    lines = [
        "# Blender Developer Tools rules (Claude Code)",
        "",
        "<!-- Generated by scripts/build_claude_rules.py from rules/*.mdc. Do not edit. -->",
        "",
        "Apply these when writing or reviewing Blender Python. Each rule links to the",
        "full version with Wrong/Right examples.",
        "",
    ]
    for path in sorted((REPO / "rules").glob("*.mdc")):
        desc, globs = parse(path)
        lines += [
            f"## {path.stem}",
            "",
            desc,
            "",
            f"Applies to: {', '.join(f'`{g}`' for g in globs) or 'n/a'}. Full rule: [`rules/{path.name}`]({RULE_URL}{path.name}).",
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def outputs() -> dict[Path, str]:
    body = render()
    return {OUT: body, SKILL_OUT: SKILL_FRONT + body}


def main() -> int:
    if "--check" in sys.argv:
        stale = []
        for path, new in outputs().items():
            old = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""
            if old != new:
                stale.append(path.relative_to(REPO).as_posix())
        if stale:
            print(f"{', '.join(stale)} stale; run python scripts/build_claude_rules.py",
                  file=sys.stderr)
            return 1
        print("claude/blender-rules.md and claude/skills/blender-rules/SKILL.md are up to date")
        return 0
    for path, new in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
